# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWinC.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindowC(object):
    def setupUi(self, MainWindowC):
        MainWindowC.setObjectName("MainWindowC")
        MainWindowC.resize(800, 600)
        MainWindowC.setMinimumSize(QtCore.QSize(800, 600))
        MainWindowC.setMaximumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/idol.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindowC.setWindowIcon(icon)
        MainWindowC.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        MainWindowC.setDocumentMode(True)
        self.centralwidget = QtWidgets.QWidget(MainWindowC)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(5, 5, 790, 550))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab0 = QtWidgets.QWidget()
        self.tab0.setObjectName("tab0")
        self.widget_2 = QtWidgets.QWidget(self.tab0)
        self.widget_2.setGeometry(QtCore.QRect(250, 40, 491, 431))
        self.widget_2.setObjectName("widget_2")
        self.YGM_B = QtWidgets.QPushButton(self.widget_2)
        self.YGM_B.setGeometry(QtCore.QRect(0, 0, 161, 161))
        self.YGM_B.setStyleSheet("font: 75 24pt \"Heiti SC\";")
        self.YGM_B.setObjectName("YGM_B")
        self.KQM_B = QtWidgets.QPushButton(self.widget_2)
        self.KQM_B.setGeometry(QtCore.QRect(320, 0, 161, 161))
        self.KQM_B.setStyleSheet("font: 75 24pt \"Heiti SC\";\n"
"")
        self.KQM_B.setObjectName("KQM_B")
        self.JBM_B = QtWidgets.QPushButton(self.widget_2)
        self.JBM_B.setGeometry(QtCore.QRect(149, 149, 182, 133))
        self.JBM_B.setStyleSheet("\n"
"font: 75 24pt \"Heiti SC\";\n"
"")
        self.JBM_B.setObjectName("JBM_B")
        self.GZM_B = QtWidgets.QPushButton(self.widget_2)
        self.GZM_B.setGeometry(QtCore.QRect(0, 270, 161, 161))
        self.GZM_B.setStyleSheet("\n"
"font: 75 24pt \"Heiti SC\";\n"
"")
        self.GZM_B.setObjectName("GZM_B")
        self.JBGZ_B = QtWidgets.QPushButton(self.widget_2)
        self.JBGZ_B.setGeometry(QtCore.QRect(320, 270, 161, 161))
        self.JBGZ_B.setStyleSheet("font: 75 24pt \"Heiti SC\";")
        self.JBGZ_B.setObjectName("JBGZ_B")
        self.frame = QtWidgets.QFrame(self.tab0)
        self.frame.setGeometry(QtCore.QRect(20, 40, 191, 431))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 260, 171, 101))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.name1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.name1.setStyleSheet("font: 75 18pt \"Heiti SC\";")
        self.name1.setObjectName("name1")
        self.gridLayout.addWidget(self.name1, 0, 1, 1, 1)
        self.name0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.name0.setStyleSheet("font: 75 24pt \"Heiti SC\";")
        self.name0.setAlignment(QtCore.Qt.AlignCenter)
        self.name0.setObjectName("name0")
        self.gridLayout.addWidget(self.name0, 0, 0, 1, 1)
        self.ID0 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ID0.setStyleSheet("font: 75 24pt \"Heiti SC\";")
        self.ID0.setAlignment(QtCore.Qt.AlignCenter)
        self.ID0.setObjectName("ID0")
        self.gridLayout.addWidget(self.ID0, 1, 0, 1, 1)
        self.ID1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ID1.setStyleSheet("font: 75 18pt \"Heiti SC\";")
        self.ID1.setObjectName("ID1")
        self.gridLayout.addWidget(self.ID1, 1, 1, 1, 1)
        self.GRM_B = QtWidgets.QPushButton(self.frame)
        self.GRM_B.setGeometry(QtCore.QRect(10, 30, 171, 171))
        self.GRM_B.setText("")
        self.GRM_B.setObjectName("GRM_B")
        self.tabWidget.addTab(self.tab0, "")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.Photo_L1 = QtWidgets.QLabel(self.tab1)
        self.Photo_L1.setGeometry(QtCore.QRect(310, 6, 171, 171))
        self.Photo_L1.setText("")
        self.Photo_L1.setAlignment(QtCore.Qt.AlignCenter)
        self.Photo_L1.setObjectName("Photo_L1")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab1)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(90, 190, 271, 291))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ID_L2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.ID_L2.setStyleSheet("font: 75 24pt \"Heiti SC\";")
        self.ID_L2.setObjectName("ID_L2")
        self.gridLayout_2.addWidget(self.ID_L2, 1, 0, 1, 1)
        self.SEX_L2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.SEX_L2.setStyleSheet("font: 75 24pt \"Heiti SC\";")
        self.SEX_L2.setObjectName("SEX_L2")
        self.gridLayout_2.addWidget(self.SEX_L2, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setStyleSheet("font: 75 24pt \"Heiti SC\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setStyleSheet("font: 75 24pt \"Heiti SC\";")
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 1, 1, 1)
        self.name_L2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.name_L2.setStyleSheet("font: 75 24pt \"Heiti SC\";\n"
"")
        self.name_L2.setObjectName("name_L2")
        self.gridLayout_2.addWidget(self.name_L2, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setStyleSheet("font: 75 24pt \"Heiti SC\";")
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 1, 1, 1)
        self.Age_L2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.Age_L2.setStyleSheet("font: 75 24pt \"Heiti SC\";")
        self.Age_L2.setObjectName("Age_L2")
        self.gridLayout_2.addWidget(self.Age_L2, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setStyleSheet("font: 75 24pt \"Heiti SC\";")
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 1, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab1)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(420, 190, 282, 291))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_14.setStyleSheet("font: 75 24pt \"Heiti SC\";")
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_12.setStyleSheet("font: 75 24pt \"Heiti SC\";")
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 1, 1, 1, 1)
        self.BMID_L2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.BMID_L2.setStyleSheet("font: 75 24pt \"Heiti SC\";")
        self.BMID_L2.setObjectName("BMID_L2")
        self.gridLayout_3.addWidget(self.BMID_L2, 0, 0, 1, 1)
        self.ZW_L2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.ZW_L2.setStyleSheet("font: 75 24pt \"Heiti SC\";")
        self.ZW_L2.setObjectName("ZW_L2")
        self.gridLayout_3.addWidget(self.ZW_L2, 1, 0, 1, 1)
        self.WORKAGE_L2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.WORKAGE_L2.setStyleSheet("font: 75 24pt \"Heiti SC\";")
        self.WORKAGE_L2.setObjectName("WORKAGE_L2")
        self.gridLayout_3.addWidget(self.WORKAGE_L2, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_10.setStyleSheet("font: 75 24pt \"Heiti SC\";")
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 1, 1, 1)
        self.LD_L = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.LD_L.setStyleSheet("font: 75 24pt \"Heiti SC\";")
        self.LD_L.setObjectName("LD_L")
        self.gridLayout_3.addWidget(self.LD_L, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_3.setStyleSheet("font: 75 24pt \"Heiti SC\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 3, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.tab1)
        self.frame_2.setGeometry(QtCore.QRect(60, 180, 671, 311))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.YGGLTable = QtWidgets.QTableWidget(self.tab2)
        self.YGGLTable.setGeometry(QtCore.QRect(150, 20, 621, 491))
        self.YGGLTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.YGGLTable.setTabKeyNavigation(False)
        self.YGGLTable.setAlternatingRowColors(True)
        self.YGGLTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.YGGLTable.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.YGGLTable.setGridStyle(QtCore.Qt.DashDotDotLine)
        self.YGGLTable.setRowCount(0)
        self.YGGLTable.setColumnCount(4)
        self.YGGLTable.setObjectName("YGGLTable")
        item = QtWidgets.QTableWidgetItem()
        self.YGGLTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.YGGLTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.YGGLTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.YGGLTable.setHorizontalHeaderItem(3, item)
        self.YGGLTable.horizontalHeader().setCascadingSectionResizes(True)
        self.YGGLTable.horizontalHeader().setDefaultSectionSize(157)
        self.YGGLTable.horizontalHeader().setHighlightSections(True)
        self.YGGLTable.horizontalHeader().setSortIndicatorShown(False)
        self.YGGLTable.horizontalHeader().setStretchLastSection(True)
        self.YGGLTable.verticalHeader().setVisible(False)
        self.BM_BOX = QtWidgets.QComboBox(self.tab2)
        self.BM_BOX.setGeometry(QtCore.QRect(10, 60, 131, 31))
        self.BM_BOX.setObjectName("BM_BOX")
        self.YGBM_L = QtWidgets.QLabel(self.tab2)
        self.YGBM_L.setGeometry(QtCore.QRect(10, 40, 130, 20))
        self.YGBM_L.setStyleSheet("font: 18pt \".SF NS Text\";\n"
"border-color: rgb(184, 183, 185);")
        self.YGBM_L.setAlignment(QtCore.Qt.AlignCenter)
        self.YGBM_L.setObjectName("YGBM_L")
        self.YDXB_L = QtWidgets.QLabel(self.tab2)
        self.YDXB_L.setGeometry(QtCore.QRect(10, 120, 130, 20))
        self.YDXB_L.setStyleSheet("\n"
"font: 18pt \".SF NS Text\";")
        self.YDXB_L.setAlignment(QtCore.Qt.AlignCenter)
        self.YDXB_L.setObjectName("YDXB_L")
        self.SEX_BOX = QtWidgets.QComboBox(self.tab2)
        self.SEX_BOX.setGeometry(QtCore.QRect(10, 141, 131, 31))
        self.SEX_BOX.setObjectName("SEX_BOX")
        self.YGGL_L = QtWidgets.QLabel(self.tab2)
        self.YGGL_L.setGeometry(QtCore.QRect(10, 207, 71, 20))
        self.YGGL_L.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.YGGL_L.setAlignment(QtCore.Qt.AlignCenter)
        self.YGGL_L.setObjectName("YGGL_L")
        self.GLspinBox1 = QtWidgets.QSpinBox(self.tab2)
        self.GLspinBox1.setGeometry(QtCore.QRect(14, 237, 48, 24))
        self.GLspinBox1.setObjectName("GLspinBox1")
        self.label = QtWidgets.QLabel(self.tab2)
        self.label.setGeometry(QtCore.QRect(65, 241, 16, 16))
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.GLspinBox2 = QtWidgets.QSpinBox(self.tab2)
        self.GLspinBox2.setGeometry(QtCore.QRect(90, 237, 48, 24))
        self.GLspinBox2.setObjectName("GLspinBox2")
        self.YGGLSearch_B = QtWidgets.QPushButton(self.tab2)
        self.YGGLSearch_B.setGeometry(QtCore.QRect(20, 470, 117, 41))
        self.YGGLSearch_B.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.YGGLSearch_B.setAutoDefault(True)
        self.YGGLSearch_B.setObjectName("YGGLSearch_B")
        self.GL_CK = QtWidgets.QCheckBox(self.tab2)
        self.GL_CK.setGeometry(QtCore.QRect(100, 206, 21, 21))
        self.GL_CK.setObjectName("GL_CK")
        self.XM_Line1 = QtWidgets.QLineEdit(self.tab2)
        self.XM_Line1.setGeometry(QtCore.QRect(10, 320, 130, 20))
        self.XM_Line1.setObjectName("XM_Line1")
        self.YDXB_L_2 = QtWidgets.QLabel(self.tab2)
        self.YDXB_L_2.setGeometry(QtCore.QRect(10, 290, 70, 20))
        self.YDXB_L_2.setStyleSheet("\n"
"font: 18pt \".SF NS Text\";")
        self.YDXB_L_2.setAlignment(QtCore.Qt.AlignCenter)
        self.YDXB_L_2.setObjectName("YDXB_L_2")
        self.XM_CK = QtWidgets.QCheckBox(self.tab2)
        self.XM_CK.setGeometry(QtCore.QRect(100, 290, 21, 21))
        self.XM_CK.setObjectName("XM_CK")
        self.YDXB_L_3 = QtWidgets.QLabel(self.tab2)
        self.YDXB_L_3.setGeometry(QtCore.QRect(10, 370, 70, 20))
        self.YDXB_L_3.setStyleSheet("\n"
"font: 18pt \".SF NS Text\";")
        self.YDXB_L_3.setAlignment(QtCore.Qt.AlignCenter)
        self.YDXB_L_3.setObjectName("YDXB_L_3")
        self.GH_CK = QtWidgets.QCheckBox(self.tab2)
        self.GH_CK.setGeometry(QtCore.QRect(100, 370, 21, 21))
        self.GH_CK.setObjectName("GH_CK")
        self.GH_Line1 = QtWidgets.QLineEdit(self.tab2)
        self.GH_Line1.setGeometry(QtCore.QRect(10, 400, 130, 21))
        self.GH_Line1.setObjectName("GH_Line1")
        self.tabWidget.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.KQ_Table = QtWidgets.QTableWidget(self.tab3)
        self.KQ_Table.setGeometry(QtCore.QRect(150, 20, 621, 491))
        self.KQ_Table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.KQ_Table.setAlternatingRowColors(True)
        self.KQ_Table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.KQ_Table.setGridStyle(QtCore.Qt.DashDotDotLine)
        self.KQ_Table.setRowCount(0)
        self.KQ_Table.setColumnCount(5)
        self.KQ_Table.setObjectName("KQ_Table")
        item = QtWidgets.QTableWidgetItem()
        self.KQ_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.KQ_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.KQ_Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.KQ_Table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.KQ_Table.setHorizontalHeaderItem(4, item)
        self.KQ_Table.horizontalHeader().setCascadingSectionResizes(True)
        self.KQ_Table.horizontalHeader().setDefaultSectionSize(121)
        self.KQ_Table.horizontalHeader().setHighlightSections(True)
        self.KQ_Table.horizontalHeader().setSortIndicatorShown(False)
        self.KQ_Table.horizontalHeader().setStretchLastSection(True)
        self.KQ_Table.verticalHeader().setVisible(False)
        self.KQJL_L = QtWidgets.QLabel(self.tab3)
        self.KQJL_L.setGeometry(QtCore.QRect(10, 85, 130, 20))
        self.KQJL_L.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.KQJL_L.setAlignment(QtCore.Qt.AlignCenter)
        self.KQJL_L.setObjectName("KQJL_L")
        self.BM_BOX_2 = QtWidgets.QComboBox(self.tab3)
        self.BM_BOX_2.setGeometry(QtCore.QRect(10, 33, 131, 31))
        self.BM_BOX_2.setObjectName("BM_BOX_2")
        self.KQJL_L_2 = QtWidgets.QLabel(self.tab3)
        self.KQJL_L_2.setGeometry(QtCore.QRect(10, 17, 130, 20))
        self.KQJL_L_2.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.KQJL_L_2.setAlignment(QtCore.Qt.AlignCenter)
        self.KQJL_L_2.setObjectName("KQJL_L_2")
        self.JL_BOX = QtWidgets.QComboBox(self.tab3)
        self.JL_BOX.setGeometry(QtCore.QRect(10, 100, 131, 31))
        self.JL_BOX.setObjectName("JL_BOX")
        self.YDXB_L_4 = QtWidgets.QLabel(self.tab3)
        self.YDXB_L_4.setGeometry(QtCore.QRect(20, 286, 70, 20))
        self.YDXB_L_4.setStyleSheet("\n"
"font: 18pt \".SF NS Text\";")
        self.YDXB_L_4.setAlignment(QtCore.Qt.AlignCenter)
        self.YDXB_L_4.setObjectName("YDXB_L_4")
        self.XM_CK_2 = QtWidgets.QCheckBox(self.tab3)
        self.XM_CK_2.setGeometry(QtCore.QRect(100, 286, 21, 21))
        self.XM_CK_2.setObjectName("XM_CK_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab3)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 310, 130, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.YDXB_L_5 = QtWidgets.QLabel(self.tab3)
        self.YDXB_L_5.setGeometry(QtCore.QRect(20, 350, 70, 20))
        self.YDXB_L_5.setStyleSheet("\n"
"font: 18pt \".SF NS Text\";")
        self.YDXB_L_5.setAlignment(QtCore.Qt.AlignCenter)
        self.YDXB_L_5.setObjectName("YDXB_L_5")
        self.GH_CK_2 = QtWidgets.QCheckBox(self.tab3)
        self.GH_CK_2.setGeometry(QtCore.QRect(100, 350, 21, 21))
        self.GH_CK_2.setObjectName("GH_CK_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab3)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 380, 130, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.KQsearch_B = QtWidgets.QPushButton(self.tab3)
        self.KQsearch_B.setGeometry(QtCore.QRect(20, 460, 117, 41))
        self.KQsearch_B.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.KQsearch_B.setAutoDefault(True)
        self.KQsearch_B.setObjectName("KQsearch_B")
        self.label_5 = QtWidgets.QLabel(self.tab3)
        self.label_5.setGeometry(QtCore.QRect(40, 140, 71, 20))
        self.label_5.setStyleSheet("font: 75 18pt \"Heiti SC\";")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.tab3)
        self.label_7.setGeometry(QtCore.QRect(40, 200, 81, 20))
        self.label_7.setStyleSheet("font: 75 18pt \"Heiti SC\";")
        self.label_7.setObjectName("label_7")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.tab3)
        self.dateEdit_2.setGeometry(QtCore.QRect(15, 160, 130, 27))
        self.dateEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 2, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_2.setDate(QtCore.QDate(2018, 2, 1))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.dateEdit_3 = QtWidgets.QDateEdit(self.tab3)
        self.dateEdit_3.setGeometry(QtCore.QRect(15, 220, 130, 27))
        self.dateEdit_3.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 2, 2), QtCore.QTime(0, 0, 0)))
        self.dateEdit_3.setDate(QtCore.QDate(2018, 2, 2))
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.tabWidget.addTab(self.tab3, "")
        self.tab4 = QtWidgets.QWidget()
        self.tab4.setObjectName("tab4")
        self.JB_Table = QtWidgets.QTableWidget(self.tab4)
        self.JB_Table.setGeometry(QtCore.QRect(150, 20, 621, 491))
        self.JB_Table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.JB_Table.setAlternatingRowColors(True)
        self.JB_Table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.JB_Table.setGridStyle(QtCore.Qt.DashDotDotLine)
        self.JB_Table.setRowCount(0)
        self.JB_Table.setColumnCount(5)
        self.JB_Table.setObjectName("JB_Table")
        item = QtWidgets.QTableWidgetItem()
        self.JB_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.JB_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.JB_Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.JB_Table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.JB_Table.setHorizontalHeaderItem(4, item)
        self.JB_Table.horizontalHeader().setCascadingSectionResizes(True)
        self.JB_Table.horizontalHeader().setDefaultSectionSize(120)
        self.JB_Table.horizontalHeader().setHighlightSections(True)
        self.JB_Table.horizontalHeader().setSortIndicatorShown(False)
        self.JB_Table.horizontalHeader().setStretchLastSection(True)
        self.JB_Table.verticalHeader().setVisible(False)
        self.KQJL_L_3 = QtWidgets.QLabel(self.tab4)
        self.KQJL_L_3.setGeometry(QtCore.QRect(10, 40, 130, 20))
        self.KQJL_L_3.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.KQJL_L_3.setAlignment(QtCore.Qt.AlignCenter)
        self.KQJL_L_3.setObjectName("KQJL_L_3")
        self.BM_BOX_4 = QtWidgets.QComboBox(self.tab4)
        self.BM_BOX_4.setGeometry(QtCore.QRect(10, 60, 131, 31))
        self.BM_BOX_4.setObjectName("BM_BOX_4")
        self.dateEdit_5 = QtWidgets.QDateEdit(self.tab4)
        self.dateEdit_5.setGeometry(QtCore.QRect(14, 154, 130, 27))
        self.dateEdit_5.setMaximumDate(QtCore.QDate(2020, 12, 31))
        self.dateEdit_5.setMinimumDate(QtCore.QDate(2017, 9, 14))
        self.dateEdit_5.setDate(QtCore.QDate(2018, 2, 1))
        self.dateEdit_5.setObjectName("dateEdit_5")
        self.YDXB_L_6 = QtWidgets.QLabel(self.tab4)
        self.YDXB_L_6.setGeometry(QtCore.QRect(20, 290, 71, 20))
        self.YDXB_L_6.setStyleSheet("\n"
"font: 18pt \".SF NS Text\";")
        self.YDXB_L_6.setAlignment(QtCore.Qt.AlignCenter)
        self.YDXB_L_6.setObjectName("YDXB_L_6")
        self.YDXB_L_7 = QtWidgets.QLabel(self.tab4)
        self.YDXB_L_7.setGeometry(QtCore.QRect(40, 130, 71, 20))
        self.YDXB_L_7.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.YDXB_L_7.setAlignment(QtCore.Qt.AlignCenter)
        self.YDXB_L_7.setObjectName("YDXB_L_7")
        self.GL_CK_7 = QtWidgets.QCheckBox(self.tab4)
        self.GL_CK_7.setGeometry(QtCore.QRect(100, 290, 21, 21))
        self.GL_CK_7.setObjectName("GL_CK_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab4)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 320, 130, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab4)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 410, 130, 21))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.YDXB_L_8 = QtWidgets.QLabel(self.tab4)
        self.YDXB_L_8.setGeometry(QtCore.QRect(20, 380, 71, 20))
        self.YDXB_L_8.setStyleSheet("\n"
"font: 18pt \".SF NS Text\";")
        self.YDXB_L_8.setAlignment(QtCore.Qt.AlignCenter)
        self.YDXB_L_8.setObjectName("YDXB_L_8")
        self.GL_CK_8 = QtWidgets.QCheckBox(self.tab4)
        self.GL_CK_8.setGeometry(QtCore.QRect(100, 380, 21, 21))
        self.GL_CK_8.setObjectName("GL_CK_8")
        self.JBsearch_B = QtWidgets.QPushButton(self.tab4)
        self.JBsearch_B.setGeometry(QtCore.QRect(20, 460, 117, 41))
        self.JBsearch_B.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.JBsearch_B.setAutoDefault(True)
        self.JBsearch_B.setObjectName("JBsearch_B")
        self.label_9 = QtWidgets.QLabel(self.tab4)
        self.label_9.setGeometry(QtCore.QRect(40, 198, 71, 16))
        self.label_9.setStyleSheet("font: 75 18pt \"Heiti SC\";")
        self.label_9.setObjectName("label_9")
        self.dateEdit_4 = QtWidgets.QDateEdit(self.tab4)
        self.dateEdit_4.setGeometry(QtCore.QRect(14, 220, 130, 27))
        self.dateEdit_4.setDate(QtCore.QDate(2018, 2, 2))
        self.dateEdit_4.setObjectName("dateEdit_4")
        self.tabWidget.addTab(self.tab4, "")
        self.tab5 = QtWidgets.QWidget()
        self.tab5.setObjectName("tab5")
        self.YGGZ_Table = QtWidgets.QTableWidget(self.tab5)
        self.YGGZ_Table.setGeometry(QtCore.QRect(150, 20, 621, 491))
        self.YGGZ_Table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.YGGZ_Table.setAlternatingRowColors(True)
        self.YGGZ_Table.setGridStyle(QtCore.Qt.DashDotDotLine)
        self.YGGZ_Table.setRowCount(0)
        self.YGGZ_Table.setColumnCount(7)
        self.YGGZ_Table.setObjectName("YGGZ_Table")
        item = QtWidgets.QTableWidgetItem()
        self.YGGZ_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.YGGZ_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.YGGZ_Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.YGGZ_Table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.YGGZ_Table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.YGGZ_Table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.YGGZ_Table.setHorizontalHeaderItem(6, item)
        self.YGGZ_Table.horizontalHeader().setCascadingSectionResizes(True)
        self.YGGZ_Table.horizontalHeader().setDefaultSectionSize(87)
        self.YGGZ_Table.horizontalHeader().setHighlightSections(True)
        self.YGGZ_Table.horizontalHeader().setSortIndicatorShown(False)
        self.YGGZ_Table.horizontalHeader().setStretchLastSection(True)
        self.YGGZ_Table.verticalHeader().setVisible(False)
        self.KQJL_L_4 = QtWidgets.QLabel(self.tab5)
        self.KQJL_L_4.setGeometry(QtCore.QRect(10, 40, 130, 20))
        self.KQJL_L_4.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.KQJL_L_4.setAlignment(QtCore.Qt.AlignCenter)
        self.KQJL_L_4.setObjectName("KQJL_L_4")
        self.BM_BOX_5 = QtWidgets.QComboBox(self.tab5)
        self.BM_BOX_5.setGeometry(QtCore.QRect(10, 60, 131, 31))
        self.BM_BOX_5.setObjectName("BM_BOX_5")
        self.YDXB_L_9 = QtWidgets.QLabel(self.tab5)
        self.YDXB_L_9.setGeometry(QtCore.QRect(20, 180, 71, 20))
        self.YDXB_L_9.setStyleSheet("\n"
"font: 18pt \".SF NS Text\";")
        self.YDXB_L_9.setAlignment(QtCore.Qt.AlignCenter)
        self.YDXB_L_9.setObjectName("YDXB_L_9")
        self.XM_CK_9 = QtWidgets.QCheckBox(self.tab5)
        self.XM_CK_9.setGeometry(QtCore.QRect(100, 180, 21, 21))
        self.XM_CK_9.setObjectName("XM_CK_9")
        self.YDXB_L_10 = QtWidgets.QLabel(self.tab5)
        self.YDXB_L_10.setGeometry(QtCore.QRect(20, 260, 71, 20))
        self.YDXB_L_10.setStyleSheet("\n"
"font: 18pt \".SF NS Text\";")
        self.YDXB_L_10.setAlignment(QtCore.Qt.AlignCenter)
        self.YDXB_L_10.setObjectName("YDXB_L_10")
        self.GH_CK_10 = QtWidgets.QCheckBox(self.tab5)
        self.GH_CK_10.setGeometry(QtCore.QRect(100, 260, 21, 21))
        self.GH_CK_10.setObjectName("GH_CK_10")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab5)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 220, 130, 21))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab5)
        self.lineEdit_8.setGeometry(QtCore.QRect(10, 290, 130, 21))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.YGGZsearch_B = QtWidgets.QPushButton(self.tab5)
        self.YGGZsearch_B.setGeometry(QtCore.QRect(20, 350, 117, 41))
        self.YGGZsearch_B.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.YGGZsearch_B.setAutoDefault(True)
        self.YGGZsearch_B.setObjectName("YGGZsearch_B")
        self.DC_B = QtWidgets.QPushButton(self.tab5)
        self.DC_B.setGeometry(QtCore.QRect(20, 441, 117, 41))
        self.DC_B.setStyleSheet("font: 75 18pt \"Heiti SC\";")
        self.DC_B.setObjectName("DC_B")
        self.MonthEdit = QtWidgets.QDateEdit(self.tab5)
        self.MonthEdit.setGeometry(QtCore.QRect(14, 140, 130, 27))
        self.MonthEdit.setDate(QtCore.QDate(2018, 2, 1))
        self.MonthEdit.setObjectName("MonthEdit")
        self.label_11 = QtWidgets.QLabel(self.tab5)
        self.label_11.setGeometry(QtCore.QRect(45, 110, 60, 16))
        self.label_11.setStyleSheet("font: 75 18pt \"Heiti SC\";")
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.tab5, "")
        self.tab6 = QtWidgets.QWidget()
        self.tab6.setObjectName("tab6")
        self.JBGZ_Table = QtWidgets.QTableWidget(self.tab6)
        self.JBGZ_Table.setGeometry(QtCore.QRect(150, 20, 621, 491))
        self.JBGZ_Table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.JBGZ_Table.setAlternatingRowColors(True)
        self.JBGZ_Table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.JBGZ_Table.setGridStyle(QtCore.Qt.DashDotDotLine)
        self.JBGZ_Table.setRowCount(0)
        self.JBGZ_Table.setColumnCount(0)
        self.JBGZ_Table.setObjectName("JBGZ_Table")
        self.JBGZ_Table.horizontalHeader().setCascadingSectionResizes(True)
        self.JBGZ_Table.horizontalHeader().setDefaultSectionSize(192)
        self.JBGZ_Table.horizontalHeader().setHighlightSections(True)
        self.JBGZ_Table.horizontalHeader().setSortIndicatorShown(False)
        self.JBGZ_Table.horizontalHeader().setStretchLastSection(False)
        self.JBGZ_Table.verticalHeader().setVisible(False)
        self.BM_BOX_6 = QtWidgets.QComboBox(self.tab6)
        self.BM_BOX_6.setGeometry(QtCore.QRect(10, 60, 131, 31))
        self.BM_BOX_6.setObjectName("BM_BOX_6")
        self.ZW_BOX = QtWidgets.QComboBox(self.tab6)
        self.ZW_BOX.setGeometry(QtCore.QRect(10, 220, 131, 31))
        self.ZW_BOX.setObjectName("ZW_BOX")
        self.JBGZsarch_B = QtWidgets.QPushButton(self.tab6)
        self.JBGZsarch_B.setGeometry(QtCore.QRect(20, 460, 117, 41))
        self.JBGZsarch_B.setStyleSheet("font: 18pt \".SF NS Text\";")
        self.JBGZsarch_B.setAutoDefault(True)
        self.JBGZsarch_B.setObjectName("JBGZsarch_B")
        self.radioButton = QtWidgets.QRadioButton(self.tab6)
        self.radioButton.setGeometry(QtCore.QRect(30, 40, 100, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab6)
        self.radioButton_2.setGeometry(QtCore.QRect(30, 200, 100, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.tabWidget.addTab(self.tab6, "")
        MainWindowC.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindowC)
        self.statusbar.setObjectName("statusbar")
        MainWindowC.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindowC)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindowC.setMenuBar(self.menubar)

        self.retranslateUi(MainWindowC)
        self.tabWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindowC)

    def retranslateUi(self, MainWindowC):
        _translate = QtCore.QCoreApplication.translate
        MainWindowC.setWindowTitle(_translate("MainWindowC", "智障科技"))
        self.YGM_B.setText(_translate("MainWindowC", "员工管理"))
        self.KQM_B.setText(_translate("MainWindowC", "考勤管理"))
        self.JBM_B.setText(_translate("MainWindowC", "加班管理"))
        self.GZM_B.setText(_translate("MainWindowC", "员工工资"))
        self.JBGZ_B.setText(_translate("MainWindowC", "基本工资"))
        self.name1.setText(_translate("MainWindowC", "TextLabel"))
        self.name0.setText(_translate("MainWindowC", "姓名"))
        self.ID0.setText(_translate("MainWindowC", "工号"))
        self.ID1.setText(_translate("MainWindowC", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab0), _translate("MainWindowC", "主页"))
        self.ID_L2.setText(_translate("MainWindowC", "工号："))
        self.SEX_L2.setText(_translate("MainWindowC", "性别："))
        self.label_2.setText(_translate("MainWindowC", "TextLabel"))
        self.label_4.setText(_translate("MainWindowC", "TextLabel"))
        self.name_L2.setText(_translate("MainWindowC", "姓名："))
        self.label_6.setText(_translate("MainWindowC", "TextLabel"))
        self.Age_L2.setText(_translate("MainWindowC", "年龄："))
        self.label_8.setText(_translate("MainWindowC", "TextLabel"))
        self.label_14.setText(_translate("MainWindowC", "TextLabel"))
        self.label_12.setText(_translate("MainWindowC", "TextLabel"))
        self.BMID_L2.setText(_translate("MainWindowC", "部门："))
        self.ZW_L2.setText(_translate("MainWindowC", "职位："))
        self.WORKAGE_L2.setText(_translate("MainWindowC", "入职时间："))
        self.label_10.setText(_translate("MainWindowC", "TextLabel"))
        self.LD_L.setText(_translate("MainWindowC", "直属领导："))
        self.label_3.setText(_translate("MainWindowC", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindowC", "个人中心"))
        item = self.YGGLTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindowC", "工号"))
        item = self.YGGLTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindowC", "姓名"))
        item = self.YGGLTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindowC", "部门"))
        item = self.YGGLTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindowC", "职位"))
        self.YGBM_L.setText(_translate("MainWindowC", "部门"))
        self.YDXB_L.setText(_translate("MainWindowC", "性别"))
        self.YGGL_L.setText(_translate("MainWindowC", "工龄"))
        self.label.setText(_translate("MainWindowC", "到"))
        self.YGGLSearch_B.setText(_translate("MainWindowC", "查找"))
        self.GL_CK.setText(_translate("MainWindowC", "CheckBox"))
        self.YDXB_L_2.setText(_translate("MainWindowC", "姓名"))
        self.XM_CK.setText(_translate("MainWindowC", "CheckBox"))
        self.YDXB_L_3.setText(_translate("MainWindowC", "工号"))
        self.GH_CK.setText(_translate("MainWindowC", "CheckBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindowC", "员工管理"))
        item = self.KQ_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindowC", "姓名"))
        item = self.KQ_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindowC", "行为"))
        item = self.KQ_Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindowC", "工号"))
        item = self.KQ_Table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindowC", "日期"))
        item = self.KQ_Table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindowC", "部门"))
        self.KQJL_L.setText(_translate("MainWindowC", "记录"))
        self.KQJL_L_2.setText(_translate("MainWindowC", "部门"))
        self.YDXB_L_4.setText(_translate("MainWindowC", "姓名"))
        self.XM_CK_2.setText(_translate("MainWindowC", "CheckBox"))
        self.YDXB_L_5.setText(_translate("MainWindowC", "工号"))
        self.GH_CK_2.setText(_translate("MainWindowC", "CheckBox"))
        self.KQsearch_B.setText(_translate("MainWindowC", "查找"))
        self.label_5.setText(_translate("MainWindowC", "起始日期"))
        self.label_7.setText(_translate("MainWindowC", "截止日期"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("MainWindowC", "考勤管理"))
        item = self.JB_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindowC", "工号"))
        item = self.JB_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindowC", "姓名"))
        item = self.JB_Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindowC", "部门"))
        item = self.JB_Table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindowC", "日期"))
        item = self.JB_Table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindowC", "加班时长"))
        self.KQJL_L_3.setText(_translate("MainWindowC", "部门"))
        self.YDXB_L_6.setText(_translate("MainWindowC", "姓名"))
        self.YDXB_L_7.setText(_translate("MainWindowC", "起始日期"))
        self.GL_CK_7.setText(_translate("MainWindowC", "CheckBox"))
        self.YDXB_L_8.setText(_translate("MainWindowC", "工号"))
        self.GL_CK_8.setText(_translate("MainWindowC", "CheckBox"))
        self.JBsearch_B.setText(_translate("MainWindowC", "查找"))
        self.label_9.setText(_translate("MainWindowC", "截止日期"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab4), _translate("MainWindowC", "加班管理"))
        item = self.YGGZ_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindowC", "工号"))
        item = self.YGGZ_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindowC", "姓名"))
        item = self.YGGZ_Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindowC", "部门"))
        item = self.YGGZ_Table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindowC", "基本工资"))
        item = self.YGGZ_Table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindowC", "津贴"))
        item = self.YGGZ_Table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindowC", "扣罚"))
        item = self.YGGZ_Table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindowC", "总工资"))
        self.KQJL_L_4.setText(_translate("MainWindowC", "部门"))
        self.YDXB_L_9.setText(_translate("MainWindowC", "姓名"))
        self.XM_CK_9.setText(_translate("MainWindowC", "CheckBox"))
        self.YDXB_L_10.setText(_translate("MainWindowC", "工号"))
        self.GH_CK_10.setText(_translate("MainWindowC", "CheckBox"))
        self.YGGZsearch_B.setText(_translate("MainWindowC", "查找"))
        self.DC_B.setText(_translate("MainWindowC", "导出"))
        self.MonthEdit.setDisplayFormat(_translate("MainWindowC", "yyyy/M"))
        self.label_11.setText(_translate("MainWindowC", "结算月"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab5), _translate("MainWindowC", "员工工资"))
        self.JBGZsarch_B.setText(_translate("MainWindowC", "查找"))
        self.radioButton.setText(_translate("MainWindowC", "部门"))
        self.radioButton_2.setText(_translate("MainWindowC", "职位"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab6), _translate("MainWindowC", "基本工资"))

