# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'YGGL.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_YGGL_M(object):
    def setupUi(self, YGGL_M):
        YGGL_M.setObjectName("YGGL_M")
        YGGL_M.setEnabled(True)
        YGGL_M.resize(600, 450)
        YGGL_M.setMinimumSize(QtCore.QSize(600, 450))
        YGGL_M.setMaximumSize(QtCore.QSize(600, 450))
        self.frame = QtWidgets.QFrame(YGGL_M)
        self.frame.setGeometry(QtCore.QRect(200, 20, 391, 361))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(19, 9, 51, 341))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(200, 10, 67, 341))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.GH_L = QtWidgets.QLineEdit(self.frame)
        self.GH_L.setGeometry(QtCore.QRect(80, 40, 101, 21))
        self.GH_L.setObjectName("GH_L")
        self.XM_L = QtWidgets.QLineEdit(self.frame)
        self.XM_L.setGeometry(QtCore.QRect(80, 127, 101, 21))
        self.XM_L.setObjectName("XM_L")
        self.NL_Box = QtWidgets.QSpinBox(self.frame)
        self.NL_Box.setGeometry(QtCore.QRect(80, 213, 111, 24))
        self.NL_Box.setObjectName("NL_Box")
        self.XB_Box = QtWidgets.QComboBox(self.frame)
        self.XB_Box.setGeometry(QtCore.QRect(80, 300, 111, 26))
        self.XB_Box.setObjectName("XB_Box")
        self.BM_Box = QtWidgets.QComboBox(self.frame)
        self.BM_Box.setGeometry(QtCore.QRect(270, 40, 111, 26))
        self.BM_Box.setObjectName("BM_Box")
        self.RZ_L = QtWidgets.QDateEdit(self.frame)
        self.RZ_L.setGeometry(QtCore.QRect(270, 300, 110, 24))
        self.RZ_L.setObjectName("RZ_L")
        self.LD_L = QtWidgets.QLineEdit(self.frame)
        self.LD_L.setGeometry(QtCore.QRect(274, 127, 101, 21))
        self.LD_L.setObjectName("LD_L")
        self.ZW_Box = QtWidgets.QComboBox(self.frame)
        self.ZW_Box.setGeometry(QtCore.QRect(270, 213, 111, 26))
        self.ZW_Box.setObjectName("ZW_Box")
        self.Cancal = QtWidgets.QPushButton(YGGL_M)
        self.Cancal.setGeometry(QtCore.QRect(60, 390, 150, 50))
        self.Cancal.setStyleSheet("font: 75 14pt \"Heiti SC\";")
        self.Cancal.setObjectName("Cancal")
        self.Photo_B = QtWidgets.QPushButton(YGGL_M)
        self.Photo_B.setGeometry(QtCore.QRect(10, 100, 181, 181))
        self.Photo_B.setText("")
        self.Photo_B.setObjectName("Photo_B")
        self.Sure = QtWidgets.QPushButton(YGGL_M)
        self.Sure.setGeometry(QtCore.QRect(410, 390, 150, 50))
        self.Sure.setObjectName("Sure")

        self.retranslateUi(YGGL_M)
        QtCore.QMetaObject.connectSlotsByName(YGGL_M)

    def retranslateUi(self, YGGL_M):
        _translate = QtCore.QCoreApplication.translate
        YGGL_M.setWindowTitle(_translate("YGGL_M", "YGGL"))
        self.label.setText(_translate("YGGL_M", "工号："))
        self.label_2.setText(_translate("YGGL_M", "姓名："))
        self.label_3.setText(_translate("YGGL_M", "年龄："))
        self.label_4.setText(_translate("YGGL_M", "性别："))
        self.label_5.setText(_translate("YGGL_M", "部门："))
        self.label_6.setText(_translate("YGGL_M", "直属上司："))
        self.label_7.setText(_translate("YGGL_M", "职位："))
        self.label_8.setText(_translate("YGGL_M", "入职时间："))
        self.Cancal.setText(_translate("YGGL_M", "返回"))
        self.Sure.setText(_translate("YGGL_M", "确认"))

